name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  # Set the registry server
  REGISTRY_SERVER: ghcr.io
  # Set the image name to repository/image_name
  IMAGE_NAME: ${{ github.repository }}/example-go-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: test Go application
        run: go test ./...

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}
