name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  # Set the registry server
  REGISTRY_SERVER: ghcr.io
  
  # Set the image name to repository_name/image_name
  IMAGE_NAME: ${{ github.repository }}/example-go-app

jobs:
  ci:
    runs-on: ubuntu-latest

    # skip the job when commit message includes 'no-ci'
    if: "!contains(github.event.head_commit.message, 'no-ci')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: test Go application
        run: go test ./...

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}
